return {
-- 	"Vigemus/iron.nvim",
-- 	config = function()
-- 		local iron = require("iron.core")
-- 		local view = require("iron.view")
-- 		local common = require("iron.fts.common")
-- 
-- 		iron.setup({
-- 			config = {
-- 				scratch_repl = true,
-- 				repl_definition = {
-- 					sh = {
-- 						command = { "bash" },
-- 					},
-- 					python = {
-- 						command = { "python3" },
-- 						format = common.bracketed_paste_python,
-- 						block_dividers = { "# %%", "#%%" },
-- 					},
-- 				},
-- 				repl_filetype = function(bufnr, ft)
-- 					return ft
-- 				end,
-- 				repl_open_cmd = view.split.vertical.rightbelow(50),
-- 			},
-- 			keymaps = {
-- 				toggle_repl = "<space>srr",
-- 				restart_repl = "<space>srR",
-- 				send_motion = "<space>sc",
-- 				visual_send = "<space>sc",
-- 				send_file = "<space>sf",
-- 				send_line = "<space>sl",
-- 				send_paragraph = "<space>sp",
-- 				send_until_cursor = "<space>su",
-- 				send_mark = "<space>sm",
-- 				send_code_block = "<space>sb",
-- 				send_code_block_and_move = "<space>sn",
-- 				mark_motion = "<space>smc",
-- 				mark_visual = "<space>smc",
-- 				remove_mark = "<space>smd",
-- 				cr = "<space>s<cr>",
-- 				interrupt = "<space>s<space>",
-- 				exit = "<space>sq",
-- 				clear = "<space>scl",
-- 			},
-- 			highlight = {
-- 				italic = true,
-- 			},
-- 			ignore_blank_lines = true,
-- 		})
-- 
-- 		vim.keymap.set("n", "<space>srf", "<cmd>IronFocus<cr>")
-- 		vim.keymap.set("n", "<space>srh", "<cmd>IronHide<cr>")
-- 	end,
}
